name: samba_ci-cd

on: ['push']

env:
  REPO: setecrs/samba
  FOLDER: samba
  VERSION: ${GITHUB_REF#refs/tags/}

jobs:
  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker build latest
        run: docker build ${{env.FOLDER}} -t ${{env.REPO}}:latest
        
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
        
      - name: Docker push latest
        run: docker push ${{env.REPO}}:latest
        
      - name: Docker push - semver
        run: |
          docker tag ${{env.REPO}}:latest ${{env.REPO}}:${{env.VERSION}}
          docker push ${{env.REPO}}:${{env.VERSION}}

